import { MdOutlineArticle, MdLockOutline, MdWebhook } from "react-icons/md";
import { FaRegBell, FaCogs } from "react-icons/fa";
import { v4 as uuid } from "uuid";
import { BsGlobe2 } from "react-icons/bs";
import { FaUserLock } from "react-icons/fa6";
import { LuNetwork } from "react-icons/lu";

const generalStepsData = [
  {
    icon: <MdOutlineArticle />,
    iconBackground: "#e6e6fa",
    iconColor: "#7059ff",
    assigned_to: [],
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    condition: false,
    name: "Form",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <FaRegBell />,
    iconBackground: "#fff1d9",
    iconColor: "#ff8629",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    condition: false,
    name: "Notify",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <FaCogs />,
    iconBackground: "#EDF2F7",
    iconColor: "#848484",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    machine: true,
    requireVerifyMachine: false,
    condition: false,
    name: "Machine",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },

  {
    icon: <MdLockOutline />,
    iconBackground: "#FDE2E2",
    iconColor: "#dc143c",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: false,
    requireVerifyMachine: false,
    condition: false,
    name: "Lock Access",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <LuNetwork />,
    iconBackground: "#fddeff",
    iconColor: "#f329ff",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    isMainMultiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    condition: true,
    condition_question: "Ex: Is this item defective?",
    name: "Condition",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <MdOutlineArticle />,
    iconBackground: "#e6e6fa",
    iconColor: "#7059ff",
    assigned_to: [],
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    condition: false,
    name: "Form & Notify",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: [],
    selectedMachines: [],
  },

  {
    icon: <FaRegBell />,
    iconBackground: "#fff1d9",
    iconColor: "#ff8629",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    machine: true,
    requireVerifyMachine: false,
    condition: false,
    name: "Notify & Machine",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <FaCogs />,
    iconBackground: "#EDF2F7",
    iconColor: "#848484",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: true,

    requireVerifyMachine: false,
    condition: false,
    name: "Machine & Lock Access",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },

  {
    icon: <MdLockOutline />,
    iconBackground: "#FDE2E2",
    iconColor: "#dc143c",
    assigned_to: [],
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: false,
    requireVerifyMachine: false,
    condition: true,
    condition_question: "Ex: Is this item defective?",
    name: "Lock Access & Condition",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },
  {
    icon: <LuNetwork />,
    iconBackground: "#fddeff",
    iconColor: "#f329ff",
    assigned_to: [],
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    multiLockAccess: false,
    isMainMultiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    condition: true,
    condition_question: "Ex: Is this item defective?",
    name: "Condition & Form",
    notificationMessage: "",
    notify: false,
    notify_to: [],
    selectedMachines: [],
  },
];

export default generalStepsData;
