import { MdOutlineArticle, MdLockOutline, MdWebhook } from "react-icons/md";
import { FaRegBell, FaCogs } from "react-icons/fa";
import { v4 as uuid } from "uuid";
import { BsGlobe2 } from "react-icons/bs";
import { FaUserLock } from "react-icons/fa6";
import { LuNetwork } from "react-icons/lu";
const isMultiAssign = import.meta.env.VITE_MULTI_ASSIGN === "true";

const GeneralStepsData = [
  {
    icon: <MdOutlineArticle />,
    iconBackground: "#e6e6fa",
    iconColor: "#7059ff",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Form",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  {
    icon: <FaRegBell />,
    iconBackground: "#fff1d9",
    iconColor: "#ff8629",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Notify",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  {
    icon: <FaCogs />,
    iconBackground: "#EDF2F7",
    iconColor: "#848484",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    machine: true,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Machine",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },

  {
    icon: <MdLockOutline />,
    iconBackground: "#FDE2E2",
    iconColor: "#dc143c",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Lock Access",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  {
    icon: <LuNetwork />,
    iconBackground: "#fddeff",
    iconColor: "#f329ff",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    isMainMultiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: true,
    condition_question: "Ex: Is this item defective?",
    name: "Condition",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },

  // {
  //   icon: <BsGlobe2 />,
  //   iconBackground: "#dbfbff",
  //   iconColor: "#3cc1fa",
  //   assigned_to: isMultiAssign ? [] : { id: "" },
  //   description: "",
  //   form: false,
  // switch id to UID
  //   UID: uuid(),
  //   formQuestions: [],
  //   lockAccess: false,
  //   multiLockAccess: false,
  //   machine: false,
  //   requireVerifyMachine: false,
  //   name: "Trigger API",
  //   notificationMessage: "",
  //   notify: false,
  //   triggerAPI: true,
  //   sendWebhook: false,
  //   notify_to: isMultiAssign ? [] : { id: "" },
  //   titleTriggerAPI: "",
  //   selectedMachines: [],
  // },
  // {
  //   icon: <MdWebhook />,
  //   iconBackground: "#cffff2",
  //   iconColor: "#00bd9a",
  //   assigned_to: isMultiAssign ? [] : { id: "" },
  //   description: "",
  //   form: false,
  //   UID: uuid(),
  //   formQuestions: [],
  //   lockAccess: false,
  //   multiLockAccess: false,
  //   machine: false,
  //   requireVerifyMachine: false,
  //   name: "Webhook",
  //   notificationMessage: "",
  //   notify: false,
  //   triggerAPI: false,
  //   sendWebhook: true,
  //   notify_to: isMultiAssign ? [] : { id: "" },
  //   titleTriggerAPI: "",
  //   selectedMachines: [],
  // },
  {
    icon: <MdOutlineArticle />,
    iconBackground: "#e6e6fa",
    iconColor: "#7059ff",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Form & Notify",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },

  {
    icon: <FaRegBell />,
    iconBackground: "#fff1d9",
    iconColor: "#ff8629",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    machine: true,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Notify & Machine",
    notificationMessage: "notification sample",
    notify: true,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  {
    icon: <FaCogs />,
    iconBackground: "#EDF2F7",
    iconColor: "#848484",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: true,

    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: false,
    name: "Machine & Lock Access",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },

  {
    icon: <MdLockOutline />,
    iconBackground: "#FDE2E2",
    iconColor: "#dc143c",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: false,
    formQuestions: [],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: true,
    isMainMultiLockAccess: true,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: true,
    name: "Lock Access & Condition",
    titleTriggerAPI: "",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  {
    icon: <LuNetwork />,
    iconBackground: "#fddeff",
    iconColor: "#f329ff",
    assigned_to: isMultiAssign ? [] : { id: "" },
    description: "",
    form: true,
    formQuestions: [
      {
        id: uuid(),
        title: "Sample Question?",
        required: true,
        type: {
          title: "Text",
          format: "Short Answer",
        },
      },
    ],
    // switch id to UID
    UID: uuid(),
    lockAccess: false,
    multiLockAccess: false,
    isMainMultiLockAccess: false,
    machine: false,
    requireVerifyMachine: false,
    triggerAPI: false,
    sendWebhook: false,
    condition: true,
    condition_question: "Ex: Is this item defective?",
    name: "Condition & Form",
    notificationMessage: "",
    notify: false,
    notify_to: isMultiAssign ? [] : { id: "" },
    selectedMachines: [],
  },
  // {
  //   icon: <FaUserLock />,
  //   iconBackground: "#ffebfb",
  //   iconColor: "#dc1485",
  //   assigned_to:[isMultiAssign ? ],:{id:""}
  //   description: "",
  //   form: false,
  //   formQuestions: [],
  //   id: uuid(),
  //   lockAccess: false,
  //   multiLockAccess: true,
  //   isMainMultiLockAccess: true,
  //   machine: false,
  //   requireVerifyMachine:false,
  //   triggerAPI: true,
  //   sendWebhook: false,
  //   name: "Multi Lock Access & Trigger API",
  //   titleTriggerAPI: "",
  //   notificationMessage: "",
  //   notify: false,
  //   notify_to: isMultiAssign ? []:{id:""},
  //   selectedMachines: [],
  // },
  // {
  //   icon: <BsGlobe2 />,
  //   iconBackground: "#dbfbff",
  //   iconColor: "#3cc1fa",
  //   assigned_to:[isMultiAssign ? ],:{id:""}
  //   description: "",
  //   form: false,
  //   id: uuid(),
  //   name: "Trigger API & Webhook",
  //   lockAccess: false,
  //   multiLockAccess: false,
  //   machine: false,
  //   requireVerifyMachine:false,
  //   triggerAPI: true,
  //   sendWebhook: true,
  //   titleTriggerAPI: "",
  //   notificationMessage: "",
  //   notify: false,
  //   notify_to: isMultiAssign ? []:{id:""},
  //   selectedMachines: [],
  // },
  // {
  //   icon: <MdWebhook />,
  //   iconBackground: "#cffff2",
  //   iconColor: "#00CB94",
  //   assigned_to:[isMultiAssign ? ],:{id:""}
  //   description: "",
  //   form: true,
  //   formQuestions: [
  //     {
  //       id: uuid(),
  //       title: "Sample Question?",
  //       required: true,
  //       type: {
  //         title: "Text",
  //         format: "Short Answer",
  //       },
  //     },
  //   ],
  //   id: uuid(),
  //   name: "Webhook & Form",
  //   lockAccess: false,
  //   multiLockAccess: false,
  //   machine: false,
  //   requireVerifyMachine:false,
  //   triggerAPI: false,
  //   sendWebhook: true,
  //   titleTriggerAPI: "",
  //   notificationMessage: "",
  //   notify: false,
  //   notify_to: isMultiAssign ? []:{id:""},
  //   selectedMachines: [],
  // },
];

export default GeneralStepsData;
